# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPDR
version:      0.32
version_from: lib/IPDR.pm
installdirs:  site
requires:
    IO::Socket::SSL:               0
    Math::BigInt:                  1.77
    Test::More:                    0
    Time::HiRes:                   0
    Unicode::MapUTF8:              1.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
